# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: ruby:3.2-slim

build:
  script:
    - apt-get update -y; apt-get install -y build-essential
    - bundle
    - JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config.gitlab.yml -d ./public/
    - JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config.gitlab.yml -d ./public/pages/kinnalru/
  pages: 
    publish: public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never

sync-public-repos:
  stage: schedule
  image: ruby:3.2-alpine
  variables:
    APK_CACHE_DIR: $CI_PROJECT_DIR/.cache/apk
    DEBIAN_FRONTEND: noninteractive
    SHELL: /bin/bash
  cache:
    key: repositories-cache
    paths:
      - repositories
      - $APK_CACHE_DIR
  only:
    refs:
      - schedules
    variables:
      - $SCRIPTNAME == "skriptorium"
  script:
    - gem install skriptorium && gem update skriptorium
    - skriptorium sync --config $SKRIPTORIUM_CONFIG -v -n