title: Samoilenko Yuri
email: kinnalru@gmail.com
description: >-
  Lead developer and technical writer @ RNDSOFT  // Ruby 💕

  Тут пишу про интересное, чем занимаюсь на работе - IT, проектирование, разработка, архитектура и технологии

baseurl: "/" # the subpath of your site, e.g. /blog
url: https://kinnalru.github.io
github_username: kinnalru
repository: kinnalru/kinnalru.github.io

author:
  name: Самойленко Юрий
  email: kinnalru@gmail.com

lang: ru
timezone: Europe/Moscow
date_locale: ru
 
# Build settings
remote_theme: "jekyll/minima"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-hostname

feed:
  path: /feed.xml
  posts_limit: 50

minima:
  # Minima skin selection. Available skins are:
  #   * classic            Default, light color scheme.
  #   * dark               Dark variant of the classic skin.
  #   * auto               Adaptive skin based on the classic and dark skins.
  #   * solarized-light    Light variant of solarized color scheme.
  #   * solarized-dark     Dark variant of solarized color scheme.
  #   * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

  # nav_pages:
  #   - about.md

  show_excerpts: false
  hide_site_feed_link: false

  social_links:
    - title: Samoilenko Yuri @ GitLab
      icon: gitlab
      url: "https://gitlab.com/kinnalru"
    - title: Samoilenko Yuri @ GitHub
      icon: github
      url: "https://github.com/kinnalru"
    - title: Teletype - мой бложик
      icon: readme
      url: "https://teletype.in/@jerry_ru"
    - title: Архи DEV - мой канальчик
      icon: telegram
      url: "https://t.me/architdev"
    - title: Samoilenko Yuri @ Dev.to
      icon: dev
      url: "https://dev.to/kinnalru"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
